version: 0.0
os: linux
files:
  - source: files/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/webserver-start.sh
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
