template_path: templates/base_network.json

parameters:
    Environment: "Lab"
    AvailabilityZoneCount: "3 AZs :: 6 Subnets"
    CIDRRange: "172.22.0.0/22"
    PublicSubnetAZ1: "172.22.0.0/24"
    PublicSubnetAZ2: "172.22.1.0/24"
    PublicSubnetAZ3: "172.22.2.0/24"
    PrivateSubnetAZ1: "172.22.3.0/26"
    PrivateSubnetAZ2: "172.22.3.64/26"
    PrivateSubnetAZ3: "172.22.3.128/26"
    InstanceTenancy: "default"
    VPNGateway: "False"
